### PR TITLE
Created Classification Markings page ASTRO-259

### PR DESCRIPTION
**Pull request by amalya-rocket**
- Created new page to test with Duncan

### CODE REVIEW

**Comment by amalya-rocket** [comment]
Testing with Duncan currently. Will continue to add content later.

**Comment by amalya-rocket** [comment]
Ready for a review that can see the image size.

**Comment by amalya-rocket** [comment]
Content ready for review (see https://rocketcom.atlassian.net/browse/ASTRO-259 for more details).

Image formatting and guidelines up to reviewers. Images are all their original sizes.

**Comment by duncan-rocket** [comment]
Astro doesn’t care about the table format, I just personally find it easier to read. I cheat by the way, my text editor automatically reformats it :)

**Pull request merged**
