### PR TITLE
Update compliance rules for Checkbox and Radio Buttons

### PR DESCRIPTION
**Pull request by sknep**
Satisfies https://rocketcom.atlassian.net/browse/ASTRO-450 and https://rocketcom.atlassian.net/browse/ASTRO-443

### CODE REVIEW

**Comment by sknep** [comment]
I would argue that the commit "does not change the intent", therefore no increment is required: https://github.com/RocketCommunicationsInc/astro-uxds/blob/be0e9c97b7b0d82004a5ca2a37688db44613b4bc/_content/community/content-policy.md#33-minor-modifications-of-existing-content-on-an-existing-page

**Comment by dmcalester** [comment]
> I would argue that the commit "does not change the intent", therefore no increment is required: https://github.com/RocketCommunicationsInc/astro-uxds/blob/be0e9c97b7b0d82004a5ca2a37688db44613b4bc/_content/community/content-policy.md#33-minor-modifications-of-existing-content-on-an-existing-page

I agree based on guidance. That begs the question though what would the patch release account for? If we loosely follow semver 

X.Y.Y - breaking change
X.Y.X - non-breaking change that materially adds functionality, improves performance/stability etc …
X.X.Y - fixes a bug in a non-breaking manner

**Comment by sknep** [comment]
> X.Y.Y - breaking change
> X.Y.X - non-breaking change that materially adds functionality, improves performance/stability etc …
> X.X.Y - fixes a bug in a non-breaking manner

How about... 
X.Y.Y - a change which **modifies existing intent**, reverses or changes existing usage instructions or recommendations
X.Y.X - a change which **adds new intent**, usage instructions, recommendations
X.X.Y - a change which **clarifies or extends existing intent**, usage instructions and recommendations
-.-.-  -  fixes a typo, misspelling, broken link, wrong path, or other human/code error **without changing intent**

**Comment by sknep** [comment]
However, strict adherence to SemVer would mean every merge to master is a new release, so I can see it both ways. I'm just trying to avoid a lot of noise and people wondering why the numbers keep going up and having to document misspelling fixes in a changelog ;)

**Comment by dmcalester** [comment]
> However, strict adherence to SemVer would mean every merge to master is a new release, so I can see it both ways. I'm just trying to avoid a lot of noise and people wondering why the numbers keep going up and having to document misspelling fixes in a changelog ;)

Agreed. Tell you what. Let’s bring it up with Q and Carlos see if we can get a ruling from the ERB on what they need for compliance.

**Comment by rocketjeff** [comment]
@sknep To be the most professional and conventional, **any** change to the compliance page should bump the patch version number of compliance, even a spelling change. This relieves us of making constant judgment calls as to when _intent_ is changed. Perhaps the build system can automatically create the changelog for each revision. It's up to the consumer of compliance to notice and integrate our changes, and to have their own policy about which changes to adopt, just as when consuming open source software. Relying on, and preaching, SEMVER as _the widely used industry standard_ for consuming changing data products is our strongest defense against entering a rabbit hole of arcane, bureaucratic
 schemes.

**Comment by sknep** [comment]
This change bumps the minor version, as we've indicated that checkboxes should use Title and not Sentence case. This changes the intent of the guidance, but does not break existing implementations.

**Comment by sknep** [comment]
@dmcalester in your notifs

**Pull request merged**
