### PR TITLE
ASTRO-1168 Update Switch Documentation

### PR DESCRIPTION
**Pull request by amalyah**
https://rocketcom.atlassian.net/browse/ASTRO-1168
- Changed content from Toggle to Switch (not the meta data though) on Toggle page and Compliance info.
- Added Rules of Thumb to Toggle page.

### CODE REVIEW

**Comment by amalyah** [comment]
Ready for review by @Design-Kat @dmcalester @Cheshire89

**Review by Design-Kat — CHANGES_REQUESTED** [review]
Is it possible to change the page title and file name to switch as well, or is that going to have to be a dev project?

**Comment by amalyah** [comment]
> Is it possible to change the page title and file name to switch as well, or is that going to have to be a dev project?

Leaving that with dev since I don't know where all the links would need to be updated once that meta data is changed.

**Review by Design-Kat — APPROVED** [review]
Per @amalyah 's note that Dev will change the title and file name, everything else looks great.

**Pull request merged**
