### PR TITLE
WIP: Astro-846 Netlify CMS Config

### PR DESCRIPTION
**Pull request by im-cr**

### CODE REVIEW

**Comment by dmcalester** [comment]
@im-cr @cskerbo is this safe to close?

**Comment by im-cr** [comment]
> @im-cr @cskerbo is this safe to close?

Hey @dmcalester preferably no, need to keep this open, it's my working dev branch for changes to the netlify setup. The other branch is just for the testing team. As content changes git committed automatically to the repo by anyone making changes in the cms. Wanted to keep that separate from my actual dev branch.

**Comment by dmcalester** [comment]
> > @im-cr @cskerbo is this safe to close?
> 
> Hey @dmcalester preferably no, need to keep this open, it's my working dev branch for changes to the netlify setup. The other branch is just for the testing team. As content changes git committed automatically to the repo by anyone making changes in the cms. Wanted to keep that separate from my actual dev branch.

Thank @im-cr just doing a little end of year house cleaning. If you see any other PRs you think are ok to close go ahead and let me know or close them.

**Comment by cskerbo** [comment]
@dmcalester @im-cr Didn't we want to keep this open?

**Comment by im-cr** [comment]
@dmcalester @cskerbo 

Sorry, totally meant "no, don't close it". It's cool, the branch is still open I can push another PR or branch off and do the same.

**Comment by cskerbo** [comment]
> @dmcalester @cskerbo
> 
> Sorry, totally meant "no, don't close it". It's cool, the branch is still open I can push another PR or branch off and do the same.

No worries - I reopened for now

**Pull request closed without merging**
